# govulncheck ignore configuration
#
# This file specifies vulnerabilities that should be ignored when running
# govulncheck. Vulnerabilities are only ignored if no fix is available.
# Once a fix is released, the wrapper script will flag them automatically.
#
# Each entry must specify:
# - id: The vulnerability ID (GO-XXXX-XXXX format)
# - module: The exact module path where the vulnerability exists
# - reason: Why this vulnerability is accepted (should note "No fix available")

ignored_vulnerabilities:
  - id: GO-2025-3536
    module: github.com/openshift/hive
    reason: "No fix available - Uncontrolled Resource Consumption Vulnerability in OpenShift Hive"

  - id: GO-2025-3529
    module: github.com/openshift/hive
    reason: "No fix available - VCenter Credentials exposed via ClusterProvision in OpenShift Hive"

  - id: GO-2024-3360
    module: github.com/openshift/hive
    reason: "No fix available - RCE through AWS/Kubernetes client configuration in OpenShift Hive"

  - id: GO-2023-1901
    module: github.com/tektoncd/pipeline
    reason: "No fix available - Pipelines do not validate child UIDs in Tekton Pipeline"
